<?php

namespace ContainerXxjx8UD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FAv419zService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.FAv419z' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.FAv419z'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'notesGratitudeDiaryService' => ['privates', 'App\\Modules\\NotesGratitudeDiary\\NotesGratitudeDiaryService', 'getNotesGratitudeDiaryServiceService', true],
        ], [
            'notesGratitudeDiaryService' => 'App\\Modules\\NotesGratitudeDiary\\NotesGratitudeDiaryService',
        ]);
    }
}
