<?php

namespace ContainerXxjx8UD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_52EypX_Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.52EypX.' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.52EypX.'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'notesDairyOfSuccessService' => ['privates', 'App\\Modules\\NotesDairyOfSuccess\\NotesDairyOfSuccessService', 'getNotesDairyOfSuccessServiceService', true],
        ], [
            'notesDairyOfSuccessService' => 'App\\Modules\\NotesDairyOfSuccess\\NotesDairyOfSuccessService',
        ]);
    }
}
