<?php

namespace ContainerXxjx8UD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_DY9IPtvService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.dY9IPtv' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.dY9IPtv'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'destructorService' => ['privates', 'App\\Modules\\UserDestructor\\UserDestructorService', 'getUserDestructorServiceService', true],
        ], [
            'destructorService' => 'App\\Modules\\UserDestructor\\UserDestructorService',
        ]);
    }
}
