<?php

namespace ContainerXxjx8UD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Vfl2W_JService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.vfl2W.J' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.vfl2W.J'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'normalizer' => ['services', '.container.private.serializer', 'get_Container_Private_SerializerService', true],
            'tripDetailsService' => ['privates', 'App\\Modules\\TripDetails\\TripDetailsService', 'getTripDetailsServiceService', true],
        ], [
            'normalizer' => '?',
            'tripDetailsService' => 'App\\Modules\\TripDetails\\TripDetailsService',
        ]);
    }
}
