<?php

namespace ContainerXxjx8UD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEPickerServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Modules\EPicker\EPickerService' shared autowired service.
     *
     * @return \App\Modules\EPicker\EPickerService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Modules'.\DIRECTORY_SEPARATOR.'EPicker'.\DIRECTORY_SEPARATOR.'EPickerService.php';

        return $container->privates['App\\Modules\\EPicker\\EPickerService'] = new \App\Modules\EPicker\EPickerService(($container->privates['App\\Repository\\EPickerRepository'] ?? $container->load('getEPickerRepositoryService')));
    }
}
