<?php

namespace ContainerXxjx8UD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getImagesManagerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Helpers\FileManager\ImagesManager' shared autowired service.
     *
     * @return \App\Helpers\FileManager\ImagesManager
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Helpers'.\DIRECTORY_SEPARATOR.'FileManager'.\DIRECTORY_SEPARATOR.'ImagesManager.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Helpers'.\DIRECTORY_SEPARATOR.'FileManager'.\DIRECTORY_SEPARATOR.'FileManagerService.php';

        return $container->privates['App\\Helpers\\FileManager\\ImagesManager'] = new \App\Helpers\FileManager\ImagesManager((\dirname(__DIR__, 4).'/uploads/images/thumbnails/'), ($container->privates['App\\Helpers\\FileManager\\FileManagerService'] ?? ($container->privates['App\\Helpers\\FileManager\\FileManagerService'] = new \App\Helpers\FileManager\FileManagerService((\dirname(__DIR__, 4).'/uploads/images/')))));
    }
}
