<?php

namespace ContainerXxjx8UD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLocationAutocompleteServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Modules\LocationAutocomplete\LocationAutocompleteService' shared autowired service.
     *
     * @return \App\Modules\LocationAutocomplete\LocationAutocompleteService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Modules'.\DIRECTORY_SEPARATOR.'LocationAutocomplete'.\DIRECTORY_SEPARATOR.'LocationAutocompleteService.php';

        return $container->privates['App\\Modules\\LocationAutocomplete\\LocationAutocompleteService'] = new \App\Modules\LocationAutocomplete\LocationAutocompleteService(($container->privates['App\\Service\\Geo\\GooglePlacesApi'] ?? $container->load('getGooglePlacesApiService')), ($container->privates['App\\Modules\\LocationAutocomplete\\LocationAutocompleteRepository'] ?? $container->load('getLocationAutocompleteRepositoryService')));
    }
}
