<?php

namespace ContainerXxjx8UD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTripDetailsServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Modules\TripDetails\TripDetailsService' shared autowired service.
     *
     * @return \App\Modules\TripDetails\TripDetailsService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Modules'.\DIRECTORY_SEPARATOR.'TripDetails'.\DIRECTORY_SEPARATOR.'TripDetailsService.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Helpers'.\DIRECTORY_SEPARATOR.'FileManager'.\DIRECTORY_SEPARATOR.'FileManagerService.php';

        return $container->privates['App\\Modules\\TripDetails\\TripDetailsService'] = new \App\Modules\TripDetails\TripDetailsService(($container->privates['App\\Repository\\TripRepository'] ?? $container->load('getTripRepositoryService')), ($container->privates['App\\Repository\\MilestoneRepository'] ?? $container->load('getMilestoneRepositoryService')), ($container->privates['App\\Helpers\\FileManager\\FileManagerService'] ?? ($container->privates['App\\Helpers\\FileManager\\FileManagerService'] = new \App\Helpers\FileManager\FileManagerService((\dirname(__DIR__, 4).'/uploads/images/')))), ($container->privates['App\\Helpers\\FileManager\\ImagesManager'] ?? $container->load('getImagesManagerService')), ($container->privates['App\\Repository\\CommentRepository'] ?? $container->load('getCommentRepositoryService')));
    }
}
