<?php

namespace ContainerXxjx8UD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserProfileControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Api\V1\UserProfileController' shared autowired service.
     *
     * @return \App\Controller\Api\V1\UserProfileController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'framework-bundle'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'AbstractController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'JsonResponseTrait.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'Api'.\DIRECTORY_SEPARATOR.'V1'.\DIRECTORY_SEPARATOR.'UserProfileController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Modules'.\DIRECTORY_SEPARATOR.'UserProfile'.\DIRECTORY_SEPARATOR.'UserProfileService.php';

        $container->services['App\\Controller\\Api\\V1\\UserProfileController'] = $instance = new \App\Controller\Api\V1\UserProfileController(new \App\Modules\UserProfile\UserProfileService(($container->privates['App\\Repository\\UserRepository'] ?? $container->load('getUserRepositoryService')), ($container->privates['url_helper'] ?? $container->load('getUrlHelperService')), ($container->privates['App\\Helpers\\FileManager\\ImagesManager'] ?? $container->load('getImagesManagerService')), ($container->privates['App\\Repository\\CommentRepository'] ?? $container->load('getCommentRepositoryService'))));

        $instance->setContainer(($container->privates['.service_locator.mx0UMmY'] ?? $container->load('get_ServiceLocator_Mx0UMmYService'))->withContext('App\\Controller\\Api\\V1\\UserProfileController', $container));

        return $instance;
    }
}
