<?php

namespace Container1BxZ12E;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator__AWpzqZService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator..aWpzqZ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator..aWpzqZ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'authentication' => ['privates', 'App\\Service\\User\\Authentication', 'getAuthenticationService', true],
            'normalizer' => ['services', '.container.private.serializer', 'get_Container_Private_SerializerService', true],
        ], [
            'authentication' => 'App\\Service\\User\\Authentication',
            'normalizer' => '?',
        ]);
    }
}
