<?php

namespace Container1BxZ12E;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Klyv6ERService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.klyv6ER' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.klyv6ER'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'normalizer' => ['services', '.container.private.serializer', 'get_Container_Private_SerializerService', true],
            'searchService' => ['privates', 'App\\Modules\\Search\\SearchService', 'getSearchServiceService', true],
        ], [
            'normalizer' => '?',
            'searchService' => 'App\\Modules\\Search\\SearchService',
        ]);
    }
}
