<?php

namespace Container1BxZ12E;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Ga9MdyXService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ga9MdyX' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ga9MdyX'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'doctrine' => ['services', 'doctrine', 'getDoctrineService', true],
            'noteGratitudeDiaryRepository' => ['privates', 'App\\Repository\\NoteGratitudeDiaryRepository', 'getNoteGratitudeDiaryRepositoryService', true],
        ], [
            'doctrine' => '?',
            'noteGratitudeDiaryRepository' => 'App\\Repository\\NoteGratitudeDiaryRepository',
        ]);
    }
}
