<?php

namespace Container1BxZ12E;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_5ZAmtr_Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.5ZAmtr.' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.5ZAmtr.'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'authentication' => ['privates', 'App\\Service\\User\\Authentication', 'getAuthenticationService', true],
        ], [
            'authentication' => 'App\\Service\\User\\Authentication',
        ]);
    }
}
