<?php

namespace Container1BxZ12E;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_77HBTzzService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.77HBTzz' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.77HBTzz'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'detailsService' => ['privates', 'App\\Modules\\LocationDetails\\LocationDetailsService', 'getLocationDetailsServiceService', true],
            'normalizer' => ['services', '.container.private.serializer', 'get_Container_Private_SerializerService', true],
        ], [
            'detailsService' => 'App\\Modules\\LocationDetails\\LocationDetailsService',
            'normalizer' => '?',
        ]);
    }
}
