<?php

namespace Container1BxZ12E;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_57nttGService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.57ntt_G' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.57ntt_G'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'travelpayoutsIATAParser' => ['privates', 'App\\Helpers\\TravelpayoutsIATAParser', 'getTravelpayoutsIATAParserService', true],
        ], [
            'travelpayoutsIATAParser' => 'App\\Helpers\\TravelpayoutsIATAParser',
        ]);
    }
}
