<?php

namespace Container1BxZ12E;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_CG4CzQVService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.cG4CzQV' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.cG4CzQV'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'memoryService' => ['privates', 'App\\Modules\\Memories\\MemoryService', 'getMemoryServiceService', true],
        ], [
            'memoryService' => 'App\\Modules\\Memories\\MemoryService',
        ]);
    }
}
