<?php

namespace Container1BxZ12E;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_NDN9v99Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.nDN9v99' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.nDN9v99'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'service' => ['privates', 'App\\Modules\\EPicker\\EPickerService', 'getEPickerServiceService', true],
        ], [
            'service' => 'App\\Modules\\EPicker\\EPickerService',
        ]);
    }
}
