<?php

namespace Container1BxZ12E;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_OjsoGK2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ojsoGK2' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ojsoGK2'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'normalizer' => ['services', '.container.private.serializer', 'get_Container_Private_SerializerService', true],
            'skillsListService' => ['privates', 'App\\Modules\\SkillsList\\SkillsListService', 'getSkillsListServiceService', true],
        ], [
            'normalizer' => '?',
            'skillsListService' => 'App\\Modules\\SkillsList\\SkillsListService',
        ]);
    }
}
