<?php

namespace Container1BxZ12E;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFileManagerControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Api\V1\FileManagerController' shared autowired service.
     *
     * @return \App\Controller\Api\V1\FileManagerController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'framework-bundle'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'AbstractController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'JsonResponseTrait.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'Api'.\DIRECTORY_SEPARATOR.'V1'.\DIRECTORY_SEPARATOR.'FileManagerController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Helpers'.\DIRECTORY_SEPARATOR.'FileManager'.\DIRECTORY_SEPARATOR.'FileManagerService.php';

        $container->services['App\\Controller\\Api\\V1\\FileManagerController'] = $instance = new \App\Controller\Api\V1\FileManagerController(($container->privates['App\\Helpers\\FileManager\\FileManagerService'] ?? ($container->privates['App\\Helpers\\FileManager\\FileManagerService'] = new \App\Helpers\FileManager\FileManagerService((\dirname(__DIR__, 4).'/uploads/images/')))));

        $instance->setContainer(($container->privates['.service_locator.mx0UMmY'] ?? $container->load('get_ServiceLocator_Mx0UMmYService'))->withContext('App\\Controller\\Api\\V1\\FileManagerController', $container));

        return $instance;
    }
}
