<?php

namespace Container1BxZ12E;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGooglePlacesApiService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\Geo\GooglePlacesApi' shared autowired service.
     *
     * @return \App\Service\Geo\GooglePlacesApi
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'Geo'.\DIRECTORY_SEPARATOR.'GooglePlacesApi.php';

        return $container->privates['App\\Service\\Geo\\GooglePlacesApi'] = new \App\Service\Geo\GooglePlacesApi($container->getEnv('GOOGLE_PLACES_API_KEY'), ($container->privates['App\\Repository\\AirportIATARepository'] ?? $container->load('getAirportIATARepositoryService')));
    }
}
