<?php

namespace Container1BxZ12E;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLocationDetailsServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Modules\LocationDetails\LocationDetailsService' shared autowired service.
     *
     * @return \App\Modules\LocationDetails\LocationDetailsService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Modules'.\DIRECTORY_SEPARATOR.'LocationDetails'.\DIRECTORY_SEPARATOR.'LocationDetailsService.php';

        return $container->privates['App\\Modules\\LocationDetails\\LocationDetailsService'] = new \App\Modules\LocationDetails\LocationDetailsService(($container->privates['App\\Service\\Geo\\GooglePlacesApi'] ?? $container->load('getGooglePlacesApiService')), ($container->privates['App\\Repository\\LocationRepository'] ?? $container->load('getLocationRepositoryService')), ($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')));
    }
}
