<?php

namespace Container1BxZ12E;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNotesGratitudeDiaryServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Modules\NotesGratitudeDiary\NotesGratitudeDiaryService' shared autowired service.
     *
     * @return \App\Modules\NotesGratitudeDiary\NotesGratitudeDiaryService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Modules'.\DIRECTORY_SEPARATOR.'NotesGratitudeDiary'.\DIRECTORY_SEPARATOR.'NotesGratitudeDiaryService.php';

        return $container->privates['App\\Modules\\NotesGratitudeDiary\\NotesGratitudeDiaryService'] = new \App\Modules\NotesGratitudeDiary\NotesGratitudeDiaryService(($container->privates['App\\Repository\\NoteGratitudeDiaryRepository'] ?? $container->load('getNoteGratitudeDiaryRepositoryService')));
    }
}
