<?php

namespace Container1BxZ12E;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSyncerServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Modules\Syncer\SyncerService' shared autowired service.
     *
     * @return \App\Modules\Syncer\SyncerService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Modules'.\DIRECTORY_SEPARATOR.'Syncer'.\DIRECTORY_SEPARATOR.'SyncerService.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Helpers'.\DIRECTORY_SEPARATOR.'FileManager'.\DIRECTORY_SEPARATOR.'FileManagerService.php';

        return $container->privates['App\\Modules\\Syncer\\SyncerService'] = new \App\Modules\Syncer\SyncerService(($container->privates['App\\Helpers\\FileManager\\FileManagerService'] ?? ($container->privates['App\\Helpers\\FileManager\\FileManagerService'] = new \App\Helpers\FileManager\FileManagerService((\dirname(__DIR__, 4).'/uploads/images/')))), ($container->privates['App\\Repository\\LocationRepository'] ?? $container->load('getLocationRepositoryService')), ($container->privates['App\\Repository\\UserRepository'] ?? $container->load('getUserRepositoryService')), ($container->privates['App\\Repository\\MilestoneRepository'] ?? $container->load('getMilestoneRepositoryService')), ($container->privates['App\\Repository\\TripRepository'] ?? $container->load('getTripRepositoryService')), ($container->privates['App\\Repository\\CommentRepository'] ?? $container->load('getCommentRepositoryService')), ($container->privates['App\\Repository\\CheckListRepository'] ?? $container->load('getCheckListRepositoryService')), ($container->privates['App\\Repository\\AirlineRepository'] ?? $container->load('getAirlineRepositoryService')), ($container->privates['App\\Repository\\TripUserRoleRepository'] ?? $container->load('getTripUserRoleRepositoryService')), ($container->privates['App\\Repository\\SkillRepository'] ?? $container->load('getSkillRepositoryService')), ($container->privates['App\\Repository\\MasterTypeRepository'] ?? $container->load('getMasterTypeRepositoryService')));
    }
}
