<?php

namespace Container1BxZ12E;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTripsListServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Modules\TripsList\TripsListService' shared autowired service.
     *
     * @return \App\Modules\TripsList\TripsListService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Modules'.\DIRECTORY_SEPARATOR.'TripsList'.\DIRECTORY_SEPARATOR.'TripsListService.php';

        return $container->privates['App\\Modules\\TripsList\\TripsListService'] = new \App\Modules\TripsList\TripsListService(($container->privates['App\\Repository\\TripRepository'] ?? $container->load('getTripRepositoryService')), ($container->privates['App\\Repository\\MilestoneRepository'] ?? $container->load('getMilestoneRepositoryService')), ($container->privates['App\\Helpers\\FileManager\\ImagesManager'] ?? $container->load('getImagesManagerService')));
    }
}
