<?php

namespace Container1BxZ12E;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserDestructorServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Modules\UserDestructor\UserDestructorService' shared autowired service.
     *
     * @return \App\Modules\UserDestructor\UserDestructorService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Modules'.\DIRECTORY_SEPARATOR.'UserDestructor'.\DIRECTORY_SEPARATOR.'UserDestructorService.php';

        return $container->privates['App\\Modules\\UserDestructor\\UserDestructorService'] = new \App\Modules\UserDestructor\UserDestructorService(($container->privates['App\\Repository\\UserRepository'] ?? $container->load('getUserRepositoryService')), ($container->privates['App\\Repository\\TripRepository'] ?? $container->load('getTripRepositoryService')), ($container->privates['App\\Repository\\TripUserRoleRepository'] ?? $container->load('getTripUserRoleRepositoryService')), ($container->privates['App\\Repository\\MilestoneRepository'] ?? $container->load('getMilestoneRepositoryService')), ($container->privates['App\\Repository\\CheckListRepository'] ?? $container->load('getCheckListRepositoryService')), ($container->privates['App\\Repository\\LocationRepository'] ?? $container->load('getLocationRepositoryService')), ($container->privates['App\\Repository\\CommentRepository'] ?? $container->load('getCommentRepositoryService')));
    }
}
