<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXxjx8UD\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXxjx8UD/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXxjx8UD.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXxjx8UD\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXxjx8UD\App_KernelDevDebugContainer([
    'container.build_hash' => 'Xxjx8UD',
    'container.build_id' => '3f98592b',
    'container.build_time' => 1686758893,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXxjx8UD');
