<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'blind' => [[], ['_controller' => 'App\\Controller\\BlindController::index'], [], [['text', '/']], [], [], []],
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'api_v1_carriers_list' => [[], ['_controller' => 'App\\Controller\\Api\\V1\\CarrierInfoController::getCarriersList', '_format' => 'json'], [], [['text', '/api/v1/carrier/list']], [], [], []],
    'api_v1_carriers_sync' => [[], ['_controller' => 'App\\Controller\\Api\\V1\\CarrierInfoController::loadCarriersList', '_format' => 'json'], [], [['text', '/api/v1/carrier/sync']], [], [], []],
    'api_v1_linked' => [[], ['_controller' => 'App\\Controller\\Api\\V1\\CommentsController::linked', '_format' => 'json'], [], [['text', '/api/v1/comments/linked']], [], [], []],
    'api_v1_list' => [[], ['_controller' => 'App\\Controller\\Api\\V1\\CommentsController::list', '_format' => 'json'], [], [['text', '/api/v1/comments/list']], [], [], []],
    'api_v1_e_picker' => [[], ['_controller' => 'App\\Controller\\Api\\V1\\EPickerController::index', '_format' => 'json'], [], [['text', '/api/v1/epicker']], [], [], []],
    'api_v1_get_image' => [['img'], ['_controller' => 'App\\Controller\\Api\\V1\\FileManagerController::getImage', '_format' => 'json'], [], [['variable', '/', '[^/]++', 'img', true], ['text', '/api/v1/image']], [], [], []],
    'api_v1_place_autocomplete' => [[], ['_controller' => 'App\\Controller\\Api\\V1\\PlaceController::autocomplete', '_format' => 'json'], [], [['text', '/api/v1/place/autocomplete']], [], [], []],
    'api_v1_place_get_by_id' => [[], ['_controller' => 'App\\Controller\\Api\\V1\\PlaceController::getPlace', '_format' => 'json'], [], [['text', '/api/v1/place/details']], [], [], []],
    'api_v1_place_get_by_address' => [[], ['_controller' => 'App\\Controller\\Api\\V1\\PlaceController::getPlaceByAddress', '_format' => 'json'], [], [['text', '/api/v1/place/address']], [], [], []],
    'api_v1_place_get_by_coordinates' => [[], ['_controller' => 'App\\Controller\\Api\\V1\\PlaceController::getPlaceByCoordinates', '_format' => 'json'], [], [['text', '/api/v1/place/coordinates']], [], [], []],
    'api_v1_parse_iata' => [[], ['_controller' => 'App\\Controller\\Api\\V1\\PlaceController::parseIATA', '_format' => 'json'], [], [['text', '/api/v1/place/parseIATA']], [], [], []],
    'trips_search' => [[], ['_controller' => 'App\\Controller\\Api\\V1\\SearchController::searchTrip', '_format' => 'json'], [], [['text', '/api/v1/search/trips']], [], [], []],
    'app_search' => [[], ['_controller' => 'App\\Controller\\Api\\V1\\SearchController::search', '_format' => 'json'], [], [['text', '/api/v1/search/users']], [], [], []],
    'app_skills' => [[], ['_controller' => 'App\\Controller\\Api\\V1\\SkillsController::index', '_format' => 'json'], [], [['text', '/api/v1/skills/list']], [], [], []],
    'api_v1_app_sync' => [[], ['_controller' => 'App\\Controller\\Api\\V1\\SyncController::sync', '_format' => 'json'], [], [['text', '/api/v1/sync']], [], [], []],
    'api_v1_trip_details' => [[], ['_controller' => 'App\\Controller\\Api\\V1\\TripDetailsController::index', '_format' => 'json'], [], [['text', '/api/v1/trip/details']], [], [], []],
    'api_v1_trips_list' => [[], ['_controller' => 'App\\Controller\\Api\\V1\\TripsListController::index', '_format' => 'json'], [], [['text', '/api/v1/trips/list']], [], [], []],
    'api_v1_user_register' => [[], ['_controller' => 'App\\Controller\\Api\\V1\\UserController::register', '_format' => 'json'], [], [['text', '/api/v1/user/register']], [], [], []],
    'api_v1_user_login' => [[], ['_controller' => 'App\\Controller\\Api\\V1\\UserController::login', '_format' => 'json'], [], [['text', '/api/v1/user/login']], [], [], []],
    'api_v1_user_profile' => [[], ['_controller' => 'App\\Controller\\Api\\V1\\UserProfileController::userProfile', '_format' => 'json'], [], [['text', '/api/v1/user/profile']], [], [], []],
    'api_v1_user_profile_recover' => [[], ['_controller' => 'App\\Controller\\Api\\V1\\UserProfileController::userProfileRecover', '_format' => 'json'], [], [['text', '/api/v1/user/profile/recover']], [], [], []],
    'api_v1_user_profile_check' => [[], ['_controller' => 'App\\Controller\\Api\\V1\\UserProfileController::userProfileCheck', '_format' => 'json'], [], [['text', '/api/v1/user/profile/check']], [], [], []],
    'api_v1_user_profile_update' => [[], ['_controller' => 'App\\Controller\\Api\\V1\\UserProfileController::userProfileUpdate', '_format' => 'json'], [], [['text', '/api/v1/user/profile/update']], [], [], []],
    'api_v1_user_profile_update_avatar' => [[], ['_controller' => 'App\\Controller\\Api\\V1\\UserProfileController::userProfileUpdateAvatar', '_format' => 'json'], [], [['text', '/api/v1/user/profile/update/avatar']], [], [], []],
    'api_v1_user_delete' => [[], ['_controller' => 'App\\Controller\\Api\\V1\\UserProfileController::deleteUser', '_format' => 'json'], [], [['text', '/api/v1/user/profile/delete']], [], [], []],
    'api_v1_users_list' => [[], ['_controller' => 'App\\Controller\\Api\\V1\\UsersListController::index', '_format' => 'json'], [], [['text', '/api/v1/users/list']], [], [], []],
];
